# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 猴子爱吃鱼的Blog
email: jianyingse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Coder, 专注码代码11年，专注数据库，专注MySQL。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://luckywhu.github.io" # the base hostname & protocol for your site
twitter_username: jianyingse
github_username:  luckywhu

# Build settings
markdown: kramdown
